import mongoose from "mongoose";

const OngoingJobSchema = new mongoose.Schema(
  {
    SortingOrder: Number,
    JobNo: Number,
    ReferenceNo: String,
    JobDate: Date,
    DepartmentId: Number,
    DepartmentName: String,
    JobStatusType: String,
    StatusType: String,
    CustomerName: String,
    ConsigneeName: String,
    MemberOf: String,
    ContainerToCnee: Boolean,
    dtCntrToCnee: Date,
    EmptyContainer: Boolean,
    dtEmptyCntr: Date,
    OperatingUser: String,
    UserName: String,
    SalesName: String,
    Mbl: String,
    ContainerNo: String,
    Atd: Date,
    Ata: Date,
    Etd: Date,
    Eta: Date,
    Status: String,
    blstatus: String,
    Notes: String,
    CarrierName: String,
    ArrivalDays: Number,
    TejrimDays: Number,
    DiffCntrToCnee: Number,
    CountryOfDeparture: String,
    Departure: String,
    CountryOfDestination: String,
    Destination: String,
    Tejrim: Boolean,
    TejrimDate: Date,
    JobType: String,
    FullPaid: Boolean,
    PaidDO: Boolean,
    PaidDate: Date,
    MissingDocuments: Boolean,
    MissingDocumentsDate: Date,
    PendingInvoices: Number,
    PendingCosts: Number,
    TotalInvoices: Number,
    TotalCosts: Number,
    TotalProfit: Number,
  },
  { timestamps: true }
);

export default mongoose.model("OngoingJob", OngoingJobSchema);
